# Generated by Django 3.2.7 on 2022-04-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_title', models.CharField(max_length=120)),
                ('target_lang', models.CharField(choices=[('Bengali', 'bn'), ('Gujarati', 'gu'), ('Hindi', 'hi'), ('Kannada', 'kn'), ('Malayalam', 'ml'), ('Marathi', 'mr'), ('Nepali', 'ne'), ('Oriya', 'or'), ('Punjabi', 'pa'), ('Sinhala', 'si'), ('Tamil', 'ta'), ('Telugu', 'te'), ('Urdu', 'ur')], default='Hindi', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.CharField(max_length=1000)),
                ('translated_sentence', models.CharField(max_length=1000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
    ]
